### ISSUE TITLE
doctrine:schema:update can't recognize microseconds format

### ISSUE THREAD

**Issue by sabat24** [BartoszBartniczak/Doctrine-DateTime-With-Microseconds#6]
1. I created a "normal" datetime field in my entity and made a migration.
2. I installed your package and changed annotation to 
```php
/**
 * @ORM\Column(type="datetime_microseconds")
 */
private $createdDate;
```
3. I run `php bin/console doctrine:schema:update -f` to update my DB schema - nothing happened.

Expected behaviour should be to change `datetime` field type into `datetime(6)`. What's more I changed it manually in my DB (MySQL) and run again previous command. Doctrine reverted my change from `datetime(6)` to `datetime`. 

Did I do something wrong?

Additionally I think that it's worth to add a doctrine configuration section to readme, because to make microseconds work correctly you have to register a custom type in `doctrine.yaml` config file

```yaml
doctrine:
    dbal:
        types:
            datetime_microseconds: BartoszBartniczak\Doctrine\DateTimeWithMicroseconds
```

If not you will get an error during schema update:

> Unknown column type "datetime_microseconds" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs
  during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you
  might have a problem with the cache or forgot some mapping information.

**Comment by BartoszBartniczak** [comment]
> Did I do something wrong?
No, you didn't. I didn't changed the column definition [in code](https://github.com/BartoszBartniczak/Doctrine-DateTime-With-Microseconds/blob/edfa8ea8a701a81580466637fdd516fb401020a7/src/DateTimeWithMicroseconds.php#L25), so basicly it creates a default datetime column. Of course, I haven't checked that, it is only my feeling. I could have check that in detail but, I don't think I could have do that in the next few days.

> Additionally I think that it's worth to add a doctrine configuration section to readme, because to make microseconds work correctly you have to register a custom type in doctrine.yaml config file

I will add that in the next release.

If you will find solution of the first problem, feel free to do the Pull Request.

**Comment by sabat24** [comment]
I guess I found a solution. It was indeed the `getSQLDeclaration` method. I will write some tests and then I can make PR. Probably tomorrow.

**Comment by sabat24** [comment]
```php
public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        $parentDateTimeDeclaration = $platform->getDateTimeTypeDeclarationSQL($fieldDeclaration);
        if ($platform instanceof SqlitePlatform) {
            $precision = 3;
        } else {
            $precision = 6;
        }

        return preg_replace('/(DATETIME[2]?|TIMESTAMP)(\([0-9]{1,2}\))?/', '$1('.$precision.')', $parentDateTimeDeclaration);
    }
```

It's my solution above. Main idea is to use string returned by Doctrine and then just change the precision of field type. It may not work for older DB engines which don't provide support for microseconds.

I didn't create a PR as there is one more problem with it. I don't know why, but Symfony still create a following migration

`ALTER TABLE table CHANGE created_date created_date DATETIME(6) NOT NULL`

even if that field in my DB has got exactly that type.

**Comment by BartoszBartniczak** [comment]
> I don't know why, but Symfony still create a following migration

> `ALTER TABLE table CHANGE created_date created_date DATETIME(6) NOT NULL`

I don't get it. Why do you think it is a problem? What do you expect?

**Comment by sabat24** [comment]
The migration is created each time you run `bin/console make:migration` even if there is no such need.

1. run `bin/console make:migration` on empty DB or newly created field
2. run `bin/console doctrine:migrations:migrate` 
3. run `bin/console make:migration` 

In step 3 there shouldn't be anything to migrate as you updated your DB's schema in step 2. 
I need to check `make:migration` command to verify how it compares actual DB schema with provided entity field type.

**Comment by BartoszBartniczak** [comment]
Ok, now I get it. Have you tried to clear cache? You did change the schema outside the doctrine, so maybe it tries to change the schema, because it doesn't see changes.

**Comment by BartoszBartniczak** [comment]
Just read your message again, and now I understand. There is for sure, a problem with diff mechanism. I don't know how it works either, but I think it is very interesting. Let me know if you need any help. I will try to solve it either.

**Comment by sabat24** [comment]
That method have to be overridden, too.

```php
public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }
```

Then a new migration should add a comment to the DB field with custom type name like that

`COMMENT \'(DC2Type:datetime_microseconds)\'`

You may take a look [here](https://github.com/doctrine/dbal/issues/1614)

Please note that I also changed SQL declaration to `$platform->getDateTimeTypeDeclarationSQL`
There was `DateTimeTz` before but I think that `datetime_microseconds` shouldn't use it as it's for `datetimetz` field type.
